services:
  pg:
    build:
      dockerfile: ./docker/postgres-dockerfile
      context: .
      args:
        ICHIRAN_DB_URL: "https://github.com/tshatrov/ichiran/releases/download/ichiran-260118/ichiran-260118.pgdump"
    shm_size: "1gb"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ${PWD}/docker/pgdata:/var/lib/postgresql/data

  main:
    build:
      dockerfile: ./docker/sbcl-dockerfile
      context: .

  app-db:
    image: postgres:16
    container_name: speed-reader-db-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ${PWD}/docker/app-pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"